server:
  port: 8080

# 修改
spring:
  datasource:
    url: jdbc:mysql://20.48.27.93:3306/internet2021?useUnicode=true
    username: root
    password: internet
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 10
    maxActive: 20
    minIdle: 5
    maxWait: 60000
    validationQuery: SELECT 1

